version: "3.8"
services:
  api:
    build: .
    restart: "always"
    environment:
      TG_APP: bot.py
    volumes:
      - .:/usr/src/app
    command: ["python", "bot.py"]
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - 5900:5432
volumes:
  postgres_data:
